# Homework 2 - Numpy

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [5]:
import numpy as np

A = np.array([1, 2, 3, 4])
B = np.array([4, 5, 6, 7])

vertical = np.vstack((A, B))
horizontal = np.hstack((A, B))

print(vertical)
print(horizontal)

[[1 2 3 4]
 [4 5 6 7]]
[1 2 3 4 4 5 6 7]


2. Find common elements between A and B. [Hint : Intersection of two sets]

In [6]:
common_elements = np.intersect1d(A, B)
print(common_elements)

[4]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [7]:
A = np.array([3, 5, 7, 2, 10, 12])

filtered = A[(A >= 5) & (A <= 10)]
print(filtered)

[ 5  7 10]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0


In [19]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

mask = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
filtered_rows = iris_2d[mask]

print(filtered_rows)

FileNotFoundError: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data not found.

# Homework 2 - Pandas 

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [12]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

result = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(result)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [13]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print(df[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


3. How to get the rows of a dataframe with row sum > 100?

In [14]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

rows_gt_100 = df[df.sum(axis=1) > 100]
print(rows_gt_100)

     0   1   2   3
1   28  33  14  26
2   33  38  16  26
3   16  28  38  32
5   25  31  35  37
6   25  24  25  33
7   30  31  22  37
8   27  34  36  37
9   38  33  23  12
10  18  31  24  34
13  38  39  12  21
14  38  32  33  12
